# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: IC-FOODS - The International Center for Food Ontology Operability Data and Semantics
description: IC-FOODS is building teh Internet of Food. We are a center, a community, and a conference (3C's) and knowledge base. \n We welcome individuals, groups , and corporations to join us in our efforts.
baseurl: /ic-foods # the subpath of your site, e.g. /support
url: https://ic-foods.github.io # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: Knowledge Base #Define whether this is a knowledge base, help center, or something else
use_authors: true #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: IC-FOODS
header: Building the Internet of Food
subheader: Learn more about our Center, Community, Conferences, Plans, Projects, and Participation

meta_image: odin-meta.png

# Social Links
twitter_username: ic3foods
facebook_page: ic3foods
github_username: mateolan
email: info@ic-foods.org
linkedin_page:
instagram_username: 


# Navivation
nav_item_one: Github
nav_item_one_link: https://github.com/IC-FOODS/ic-foods

nav_item_two: Twitter
nav_item_two_link: https://twitter.com/ic3foods

nav_item_three: Facebook
nav_item_three_link: https://www.facebook.com/ic3foods/

nav_button: Return to IC-FOODS Home
nav_button_link: https://ic-foods.github.io/ic-foods/

# More Help
help_one_title: IC-FOODS Bugs
help_one_content: If you find any bugs or problems with this site, please open an issue over on Github.
help_one_button: Github
help_one_link: https://github.com/IC-FOODS/ic-foods/issues

help_two_title: Twitter
help_two_content: Feel free to tweet at me if you have suggestions for IC-FOODS. Or if you just want to say hi.
help_two_button: Twitter
help_two_link: https://twitter.com/ic3foods

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
